#!/bin/sh
#
# postinst for ncftp3

set -e

update-alternatives --install /usr/bin/ncftp ncftp /usr/bin/ncftp3 10 \
  --slave /usr/share/man/man1/ncftp.1.gz ncftp.1.gz /usr/share/man/man1/ncftp3.1.gz

#DEBHELPER#
